### PR TITLE
Update CocoaPods to 1.5.3

### PR DESCRIPTION
**Pull request by jtreanor**
👋

This is just a simple PR to update CocoaPods from 1.3.1 to 1.5.3 in `Gemfile.lock`. Everything still works and the tests pass so no other updates were needed.

### CODE REVIEW

**Comment by bboyle18** [comment]
Yeah I spotted that. Looking into it now.

**Comment by jtreanor** [comment]
No panic at all. Just made these changes so I could check it out with the new Betas.

**Comment by bboyle18** [comment]
That setting has been applied now. You may need to push an empty commit to trigger it

**Comment by jtreanor** [comment]
Its green! 👏 Merge away whenever you like 😄

**Comment by jtreanor** [comment]
🎉

**Pull request merged**
